# Generated by Django 5.1.7 on 2025-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idfPhotoUrl',
            field=models.ImageField(blank=True, default='id_front_default.jpg', null=True, upload_to='users/'),
        ),
    ]
