# Generated by Django 5.1.7 on 2025-06-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_idfphotourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='serviceType',
            field=models.CharField(max_length=50),
        ),
    ]
