# Generated by Django 5.1.7 on 2025-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idPhotoUrl',
            field=models.ImageField(blank=True, default='id_default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='idfPhotoUrl',
            field=models.ImageField(blank=True, default='id_front_default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='iduserPhotoUrl',
            field=models.ImageField(blank=True, default='id_user_default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
