# Generated by Django 4.2.27 on 2025-12-15 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English name"),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("top_rated", "Top Rated"),
                            ("responsive", "Responsive"),
                            ("featured", "Featured"),
                            ("expert", "Expert"),
                            ("new_provider", "New Provider"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Badge type",
                    ),
                ),
                ("description_ar", models.TextField(verbose_name="Arabic description")),
                (
                    "description_en",
                    models.TextField(verbose_name="English description"),
                ),
                ("icon", models.CharField(max_length=50, verbose_name="Icon")),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Color"
                    ),
                ),
                (
                    "criteria_config",
                    models.JSONField(
                        default=dict, verbose_name="Criteria configuration"
                    ),
                ),
                (
                    "search_boost",
                    models.FloatField(default=1.0, verbose_name="Search ranking boost"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ["badge_type"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Earned at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False, verbose_name="Manual assignment"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Admin notes")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badges_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="trust.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
        migrations.CreateModel(
            name="TrustMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("avg_rating", "Average Rating"),
                            ("total_reviews", "Total Reviews"),
                            ("response_time_minutes", "Response Time (minutes)"),
                            ("completion_rate", "Completion Rate"),
                            ("cancellation_rate", "Cancellation Rate"),
                            ("repeat_customer_rate", "Repeat Customer Rate"),
                        ],
                        max_length=30,
                        verbose_name="Metric type",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Value")),
                ("period_start", models.DateTimeField(verbose_name="Period start")),
                ("period_end", models.DateTimeField(verbose_name="Period end")),
                (
                    "calculation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Calculated at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Metric",
                "verbose_name_plural": "Trust Metrics",
                "ordering": ["-calculation_date"],
                "unique_together": {
                    ("user", "metric_type", "period_start", "period_end")
                },
            },
        ),
    ]
