# Generated by Django 4.2.27 on 2025-12-15 00:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="Arabic title"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="English title"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description_ar", models.TextField(verbose_name="Arabic description")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="English description"),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("hourly", "Per Hour"),
                            ("package", "Package Deal"),
                            ("negotiable", "Negotiable"),
                        ],
                        default="fixed",
                        max_length=12,
                        verbose_name="Pricing type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (minutes)"
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Max participants",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection reason"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views count"),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English name"),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Yes/No"),
                            ("choice", "Multiple Choice"),
                            ("date", "Date"),
                        ],
                        max_length=10,
                        verbose_name="Attribute type",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Required"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
            ],
            options={
                "verbose_name": "Service Attribute",
                "verbose_name_plural": "Service Attributes",
                "ordering": ["sort_order", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Arabic description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="English description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Color"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["sort_order", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="ServiceSubcategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English name"),
                ),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Arabic description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="English description"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Subcategory",
                "verbose_name_plural": "Service Subcategories",
                "ordering": ["sort_order", "name_ar"],
                "unique_together": {("category", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="services/gallery/", verbose_name="Image"
                    ),
                ),
                (
                    "caption_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Arabic caption"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="English caption"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary image"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Image",
                "verbose_name_plural": "Service Images",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services_provided",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Service Owner",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.servicesubcategory",
            ),
        ),
        migrations.CreateModel(
            name="ServiceAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("value", models.TextField(verbose_name="Value")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.serviceattribute",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Attribute Value",
                "verbose_name_plural": "Service Attribute Values",
                "unique_together": {("service", "attribute")},
            },
        ),
    ]
