# Generated by Django 4.2.27 on 2025-12-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_service_center_service_governorate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Slug"),
        ),
    ]
