# Generated by Django 4.2.27 on 2025-12-15 00:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("warn", "Warning Issued"),
                            ("hide_content", "Content Hidden"),
                            ("reject_content", "Content Rejected"),
                            ("suspend_user", "User Suspended"),
                            ("block_user", "User Blocked"),
                            ("remove_content", "Content Removed"),
                            ("approve_content", "Content Approved"),
                            ("restore_content", "Content Restored"),
                            ("unblock_user", "User Unblocked"),
                            ("escalate", "Escalated to Senior"),
                        ],
                        max_length=20,
                        verbose_name="Action type",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("SPAM_001", "Commercial Spam"),
                            ("SPAM_002", "Repetitive Content"),
                            ("INAP_001", "Adult Content"),
                            ("INAP_002", "Violent Content"),
                            ("INAP_003", "Hate Speech"),
                            ("FAKE_001", "Fake Profile"),
                            ("FAKE_002", "Fake Service"),
                            ("FRAU_001", "Financial Fraud"),
                            ("FRAU_002", "Identity Theft"),
                            ("HARA_001", "Harassment"),
                            ("HARA_002", "Stalking"),
                            ("COPY_001", "Copyright Violation"),
                            ("PRIC_001", "Misleading Pricing"),
                            ("QUAL_001", "Poor Service Quality"),
                            ("LOCA_001", "Wrong Location"),
                            ("SAFE_001", "Safety Concern"),
                            ("MINO_001", "Minor Safety Issue"),
                            ("OTHE_001", "Other Violation"),
                        ],
                        max_length=10,
                        verbose_name="Reason code",
                    ),
                ),
                ("reason_text", models.TextField(verbose_name="Detailed reason")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Action expires at"
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(default=False, verbose_name="Permanent action"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Internal notes"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Moderator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Action",
                "verbose_name_plural": "Moderation Actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Template name"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("warning", "Warning Message"),
                            ("rejection", "Rejection Notice"),
                            ("suspension", "Suspension Notice"),
                            ("appeal_response", "Appeal Response"),
                            ("policy_reminder", "Policy Reminder"),
                        ],
                        max_length=20,
                        verbose_name="Template type",
                    ),
                ),
                (
                    "reason_codes",
                    models.JSONField(
                        default=list, verbose_name="Applicable reason codes"
                    ),
                ),
                (
                    "subject_ar",
                    models.CharField(max_length=200, verbose_name="Arabic subject"),
                ),
                (
                    "subject_en",
                    models.CharField(max_length=200, verbose_name="English subject"),
                ),
                ("content_ar", models.TextField(verbose_name="Arabic content")),
                ("content_en", models.TextField(verbose_name="English content")),
                (
                    "variables",
                    models.JSONField(default=list, verbose_name="Template variables"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="Usage count"),
                ),
            ],
            options={
                "verbose_name": "Moderation Template",
                "verbose_name_plural": "Moderation Templates",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserSuspension",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suspension_type",
                    models.CharField(
                        choices=[
                            ("temporary", "Temporary Suspension"),
                            ("permanent", "Permanent Ban"),
                            ("shadow", "Shadow Ban"),
                            ("feature_restriction", "Feature Restriction"),
                        ],
                        max_length=20,
                        verbose_name="Suspension type",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("SPAM_001", "Commercial Spam"),
                            ("SPAM_002", "Repetitive Content"),
                            ("INAP_001", "Adult Content"),
                            ("INAP_002", "Violent Content"),
                            ("INAP_003", "Hate Speech"),
                            ("FAKE_001", "Fake Profile"),
                            ("FAKE_002", "Fake Service"),
                            ("FRAU_001", "Financial Fraud"),
                            ("FRAU_002", "Identity Theft"),
                            ("HARA_001", "Harassment"),
                            ("HARA_002", "Stalking"),
                            ("COPY_001", "Copyright Violation"),
                            ("PRIC_001", "Misleading Pricing"),
                            ("QUAL_001", "Poor Service Quality"),
                            ("LOCA_001", "Wrong Location"),
                            ("SAFE_001", "Safety Concern"),
                            ("MINO_001", "Minor Safety Issue"),
                            ("OTHE_001", "Other Violation"),
                        ],
                        max_length=10,
                        verbose_name="Reason code",
                    ),
                ),
                ("reason_text", models.TextField(verbose_name="Reason")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(default=False, verbose_name="Permanent"),
                ),
                (
                    "restricted_features",
                    models.JSONField(default=list, verbose_name="Restricted features"),
                ),
                (
                    "can_appeal",
                    models.BooleanField(default=True, verbose_name="Can appeal"),
                ),
                (
                    "appeal_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Appeal deadline"
                    ),
                ),
                (
                    "moderation_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="moderation.moderationaction",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Moderator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Suspension",
                "verbose_name_plural": "User Suspensions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("fake", "Fake Service/Profile"),
                            ("fraud", "Fraud/Scam"),
                            ("harassment", "Harassment"),
                            ("copyright", "Copyright Violation"),
                            ("pricing", "Misleading Pricing"),
                            ("location", "Wrong Location"),
                            ("quality", "Poor Service Quality"),
                            ("violence", "Violence/Threats"),
                            ("hate_speech", "Hate Speech"),
                            ("minor_safety", "Minor Safety"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                        verbose_name="Reason",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/evidence/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "mp4",
                                    "mov",
                                ]
                            )
                        ],
                        verbose_name="Evidence",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Triage"),
                            ("triaging", "Under Triage"),
                            ("assigned", "Assigned to Moderator"),
                            ("investigating", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sla_due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA due at"
                    ),
                ),
                (
                    "first_response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="First response at"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved at"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution notes"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Internal notes"),
                ),
                (
                    "escalation_reason",
                    models.TextField(blank=True, verbose_name="Escalation reason"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned moderator",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reporter",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["sla_due_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                            ("community", "Community Guidelines"),
                            ("safety", "Safety Guidelines"),
                        ],
                        max_length=20,
                        verbose_name="Policy type",
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="Arabic title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="English title"),
                ),
                ("content_ar", models.TextField(verbose_name="Arabic content")),
                ("content_en", models.TextField(verbose_name="English content")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                ("effective_date", models.DateTimeField(verbose_name="Effective date")),
                (
                    "change_summary",
                    models.TextField(blank=True, verbose_name="Change summary"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="moderation.policyversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Version",
                "verbose_name_plural": "Policy Versions",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Acknowledged at",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="moderation.policyversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Acknowledgment",
                "verbose_name_plural": "Policy Acknowledgments",
                "ordering": ["-acknowledged_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("reports", "Reports Queue"),
                            ("appeals", "Appeals Queue"),
                            ("escalations", "Escalations Queue"),
                            ("policy_violations", "Policy Violations"),
                        ],
                        max_length=20,
                        verbose_name="Queue type",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=50, verbose_name="Priority"),
                ),
                (
                    "auto_assign",
                    models.BooleanField(default=True, verbose_name="Auto assign"),
                ),
                (
                    "sla_hours",
                    models.PositiveIntegerField(default=24, verbose_name="SLA hours"),
                ),
                (
                    "escalation_hours",
                    models.PositiveIntegerField(
                        default=48, verbose_name="Escalation hours"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "max_concurrent_items",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Max concurrent items"
                    ),
                ),
                (
                    "assigned_moderators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="moderation_queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Queue",
                "verbose_name_plural": "Moderation Queues",
                "ordering": ["priority", "queue_type"],
            },
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="moderation.report",
                verbose_name="Related report",
            ),
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_actions_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Target user",
            ),
        ),
        migrations.CreateModel(
            name="AutoModerationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Rule name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword Match"),
                            ("pattern", "Pattern Match"),
                            ("frequency", "Frequency Threshold"),
                            ("reputation", "Reputation Score"),
                            ("ml_confidence", "ML Confidence Score"),
                        ],
                        max_length=15,
                        verbose_name="Trigger type",
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(verbose_name="Trigger configuration"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("flag", "Flag for Review"),
                            ("auto_hide", "Auto Hide"),
                            ("auto_reject", "Auto Reject"),
                            ("require_review", "Require Manual Review"),
                            ("rate_limit", "Apply Rate Limit"),
                        ],
                        max_length=15,
                        verbose_name="Action type",
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(default=dict, verbose_name="Action configuration"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "trigger_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Trigger count"
                    ),
                ),
                (
                    "false_positive_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="False positives"
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(default=0.8, verbose_name="Confidence threshold"),
                ),
                (
                    "review_threshold",
                    models.FloatField(default=0.6, verbose_name="Review threshold"),
                ),
                (
                    "target_content_types",
                    models.ManyToManyField(blank=True, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "Auto Moderation Rule",
                "verbose_name_plural": "Auto Moderation Rules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appeal_text", models.TextField(verbose_name="Appeal explanation")),
                (
                    "additional_evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="appeals/evidence/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Additional evidence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Appeal Approved"),
                            ("denied", "Appeal Denied"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed at"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution notes"),
                ),
                ("sla_due_at", models.DateTimeField(verbose_name="SLA due at")),
                (
                    "appellant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderation_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to="moderation.moderationaction",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appeal",
                "verbose_name_plural": "Appeals",
                "ordering": ["sla_due_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "severity", "sla_due_at"],
                name="moderation__status_5b1318_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["assigned_to", "status"], name="moderation__assigne_ea94d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="moderation__content_408935_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policyversion",
            unique_together={("policy_type", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="policyacknowledgment",
            unique_together={("user", "policy_version")},
        ),
    ]
