# Generated by Django 4.2.27 on 2025-12-15 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Feature key"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English name"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Arabic description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="English description"),
                ),
                (
                    "required_plan_types",
                    models.JSONField(default=list, verbose_name="Required plan types"),
                ),
                (
                    "is_global",
                    models.BooleanField(default=False, verbose_name="Global feature"),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("incomplete", "Incomplete"),
                            ("trialing", "Trialing"),
                        ],
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(verbose_name="Current period start"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(verbose_name="Current period end"),
                ),
                (
                    "trial_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trial start"
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trial end"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Canceled at"
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Stripe subscription ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stripe customer ID"
                    ),
                ),
                (
                    "services_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Services count"
                    ),
                ),
                (
                    "team_members_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Team members count"
                    ),
                ),
                (
                    "featured_credits_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Featured credits used"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "services_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Services count"
                    ),
                ),
                (
                    "team_members_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Team members count"
                    ),
                ),
                (
                    "featured_credits_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Featured credits used"
                    ),
                ),
                (
                    "storage_used_mb",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Storage used (MB)"
                    ),
                ),
                (
                    "monthly_api_calls",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Monthly API calls"
                    ),
                ),
                (
                    "monthly_messages_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Monthly messages sent"
                    ),
                ),
                (
                    "last_reset_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Last reset at"
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_usage",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Usage",
                "verbose_name_plural": "Subscription Usage",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English name"),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        max_length=10,
                        verbose_name="Plan type",
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        max_length=10,
                        verbose_name="Billing period",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "max_services",
                    models.PositiveIntegerField(default=3, verbose_name="Max services"),
                ),
                (
                    "max_team_members",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Max team members"
                    ),
                ),
                (
                    "has_advanced_analytics",
                    models.BooleanField(
                        default=False, verbose_name="Advanced analytics"
                    ),
                ),
                (
                    "has_priority_support",
                    models.BooleanField(default=False, verbose_name="Priority support"),
                ),
                (
                    "search_ranking_boost",
                    models.FloatField(default=1.0, verbose_name="Search ranking boost"),
                ),
                (
                    "featured_credits_included",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Featured credits"
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stripe price ID"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Arabic description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="English description"),
                ),
                (
                    "features_ar",
                    models.JSONField(default=list, verbose_name="Arabic features"),
                ),
                (
                    "features_en",
                    models.JSONField(default=list, verbose_name="English features"),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Popular plan"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["sort_order", "price"],
                "unique_together": {("plan_type", "billing_period")},
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Invoice number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tax amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="Currency"
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="Period start")),
                ("period_end", models.DateTimeField(verbose_name="Period end")),
                ("due_date", models.DateTimeField(verbose_name="Due date")),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid at"),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stripe invoice ID"
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Stripe payment intent ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="PDF invoice",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Coupon code"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English name"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=10,
                        verbose_name="Discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Discount value"
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Max discount amount",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valid from")),
                ("valid_until", models.DateTimeField(verbose_name="Valid until")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Max uses"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="Used count"),
                ),
                (
                    "first_time_only",
                    models.BooleanField(
                        default=False, verbose_name="First time customers only"
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimum amount",
                    ),
                ),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True, to="subscriptions.subscriptionplan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company name"
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(max_length=200, verbose_name="Address line 1"),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "governorate",
                    models.CharField(max_length=100, verbose_name="Governorate"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="EG", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Tax ID"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default address"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Address",
                "verbose_name_plural": "Billing Addresses",
            },
        ),
        migrations.CreateModel(
            name="AddonCredit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("featured", "Featured Placement"),
                            ("boost", "Search Boost"),
                            ("analytics", "Advanced Analytics"),
                        ],
                        max_length=15,
                        verbose_name="Credit type",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Credit amount")),
                (
                    "used_amount",
                    models.PositiveIntegerField(default=0, verbose_name="Used amount"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires at")),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Purchase price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addon_credits",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Addon Credit",
                "verbose_name_plural": "Addon Credits",
                "ordering": ["expires_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("service_created", "Service Created"),
                            ("featured_placement", "Featured Placement"),
                            ("team_member_added", "Team Member Added"),
                            ("api_call", "API Call"),
                            ("storage_used", "Storage Used"),
                        ],
                        max_length=20,
                        verbose_name="Usage type",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="Metadata")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Unit price",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total amount",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Record",
                "verbose_name_plural": "Usage Records",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "usage_type", "timestamp"],
                        name="subscriptio_subscri_dab497_idx",
                    )
                ],
            },
        ),
    ]
