# Generated by Django 4.2.7 on 2026-03-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paymob_order_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Paymob Order ID"
            ),
        ),
    ]
