# Generated by Django 4.2.27 on 2025-12-15 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reviews", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=10,
                        verbose_name="Sentiment",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(verbose_name="Confidence score"),
                ),
                (
                    "aspects",
                    models.JSONField(default=dict, verbose_name="Aspect analysis"),
                ),
                (
                    "language_detected",
                    models.CharField(max_length=2, verbose_name="Language"),
                ),
                (
                    "model_version",
                    models.CharField(max_length=20, verbose_name="Model version"),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Sentiment",
                "verbose_name_plural": "Review Sentiments",
            },
        ),
        migrations.CreateModel(
            name="ServiceRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(verbose_name="Similarity score"),
                ),
                (
                    "algorithm_version",
                    models.CharField(max_length=20, verbose_name="Algorithm version"),
                ),
                (
                    "factors",
                    models.JSONField(
                        default=dict, verbose_name="Recommendation factors"
                    ),
                ),
                (
                    "recommended_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_to",
                        to="services.service",
                    ),
                ),
                (
                    "source_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_from",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Recommendation",
                "verbose_name_plural": "Service Recommendations",
                "ordering": ["-similarity_score"],
                "unique_together": {("source_service", "recommended_service")},
            },
        ),
        migrations.CreateModel(
            name="ProviderSentimentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="Period start")),
                ("period_end", models.DateTimeField(verbose_name="Period end")),
                (
                    "positive_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Positive reviews"
                    ),
                ),
                (
                    "neutral_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Neutral reviews"
                    ),
                ),
                (
                    "negative_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Negative reviews"
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total reviews"
                    ),
                ),
                (
                    "punctuality_score",
                    models.FloatField(default=0, verbose_name="Punctuality score"),
                ),
                (
                    "quality_score",
                    models.FloatField(default=0, verbose_name="Quality score"),
                ),
                (
                    "communication_score",
                    models.FloatField(default=0, verbose_name="Communication score"),
                ),
                (
                    "value_score",
                    models.FloatField(default=0, verbose_name="Value for money score"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Sentiment Summary",
                "verbose_name_plural": "Provider Sentiment Summaries",
                "ordering": ["-period_end"],
                "unique_together": {("provider", "period_start", "period_end")},
            },
        ),
    ]
