# Generated by Django 4.2.7 on 2026-03-14 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
        ("payments", "0002_wallet_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking Payment"),
                    ("subscription", "Subscription Plan"),
                ],
                default="booking",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="subscriptions.subscriptionplan",
                verbose_name="Subscription Plan",
            ),
        ),
    ]
