# Generated by Django 4.2.7 on 2026-02-17 19:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="notes",
        ),
        migrations.AddField(
            model_name="booking",
            name="additional_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Additional Charges",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Admin Notes"),
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(
                blank=True,
                default="TEMP",
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Booking Number",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_notes",
            field=models.TextField(blank=True, verbose_name="Cancellation Notes"),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("schedule_conflict", "Schedule Conflict"),
                    ("found_alternative", "Found Alternative"),
                    ("price_issue", "Price Issue"),
                    ("service_issue", "Service Issue"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Cancellation Reason",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelled at"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_cancelled",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cancelled by",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completed at"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_notes",
            field=models.TextField(blank=True, verbose_name="Customer Notes"),
        ),
        migrations.AddField(
            model_name="booking",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Discount",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Is Paid"),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_refunded",
            field=models.BooleanField(default=False, verbose_name="Is Refunded"),
        ),
        migrations.AddField(
            model_name="booking",
            name="location_address",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Service Location Address"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="location_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="booking",
            name="location_governorate",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Governorate"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Payment Method"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Service Provider",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="provider_notes",
            field=models.TextField(blank=True, verbose_name="Provider Notes"),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Refund Amount",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="refunded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Refunded at"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="scheduled_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Scheduled End Date"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Service Price"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="scheduled_date",
            field=models.DateTimeField(verbose_name="Scheduled Date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled_by_customer", "Cancelled by Customer"),
                    ("cancelled_by_provider", "Cancelled by Provider"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Total Amount"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="bookings_bo_custome_10bd54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["provider", "-created_at"],
                name="bookings_bo_provide_7ad8bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "-created_at"], name="bookings_bo_status_eb4fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_number"], name="bookings_bo_booking_03d631_idx"
            ),
        ),
    ]
