# Generated by Django 4.2.27 on 2025-12-15 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_users",
                    models.PositiveIntegerField(default=0, verbose_name="Total users"),
                ),
                (
                    "new_users",
                    models.PositiveIntegerField(default=0, verbose_name="New users"),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(default=0, verbose_name="Active users"),
                ),
                (
                    "verified_users",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Verified users"
                    ),
                ),
                (
                    "total_services",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total services"
                    ),
                ),
                (
                    "new_services",
                    models.PositiveIntegerField(default=0, verbose_name="New services"),
                ),
                (
                    "approved_services",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Approved services"
                    ),
                ),
                (
                    "approval_rate",
                    models.FloatField(default=0, verbose_name="Approval rate"),
                ),
                (
                    "page_views",
                    models.PositiveIntegerField(default=0, verbose_name="Page views"),
                ),
                (
                    "service_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Service views"
                    ),
                ),
                (
                    "searches",
                    models.PositiveIntegerField(default=0, verbose_name="Searches"),
                ),
                (
                    "messages",
                    models.PositiveIntegerField(default=0, verbose_name="Messages"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total revenue",
                    ),
                ),
                (
                    "commission_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Commission revenue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Analytics",
                "verbose_name_plural": "Platform Analytics",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="ProviderAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "profile_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Profile views"
                    ),
                ),
                (
                    "service_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Service views"
                    ),
                ),
                (
                    "service_clicks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Service clicks"
                    ),
                ),
                (
                    "messages_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Messages received"
                    ),
                ),
                (
                    "messages_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Messages sent"
                    ),
                ),
                (
                    "response_time_minutes",
                    models.FloatField(
                        default=0, verbose_name="Avg response time (minutes)"
                    ),
                ),
                (
                    "inquiries_count",
                    models.PositiveIntegerField(default=0, verbose_name="Inquiries"),
                ),
                (
                    "bookings_count",
                    models.PositiveIntegerField(default=0, verbose_name="Bookings"),
                ),
                (
                    "conversion_rate",
                    models.FloatField(default=0, verbose_name="Conversion rate"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Revenue",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reviews count"
                    ),
                ),
                (
                    "average_rating",
                    models.FloatField(default=0, verbose_name="Average rating"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Analytics",
                "verbose_name_plural": "Provider Analytics",
                "ordering": ["-date"],
                "unique_together": {("provider", "date")},
            },
        ),
        migrations.CreateModel(
            name="GovernorateAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "services_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Services count"
                    ),
                ),
                (
                    "providers_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Providers count"
                    ),
                ),
                (
                    "bookings_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Bookings count"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Revenue",
                    ),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="core.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Governorate Analytics",
                "verbose_name_plural": "Governorate Analytics",
                "ordering": ["-date"],
                "unique_together": {("governorate", "date")},
            },
        ),
        migrations.CreateModel(
            name="EventTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Session ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("service_view", "Service View"),
                            ("service_click", "Service Click"),
                            ("profile_view", "Profile View"),
                            ("search", "Search"),
                            ("filter_apply", "Filter Applied"),
                            ("message_sent", "Message Sent"),
                            ("booking_attempt", "Booking Attempt"),
                            ("contact_provider", "Contact Provider"),
                            ("service_share", "Service Shared"),
                            ("favorite_add", "Added to Favorites"),
                            ("review_submit", "Review Submitted"),
                        ],
                        max_length=20,
                        verbose_name="Event type",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="Event metadata"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("referrer", models.URLField(blank=True, verbose_name="Referrer")),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.city",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.province",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Tracking",
                "verbose_name_plural": "Event Tracking",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_e_event_t_1a6456_idx",
                    ),
                    models.Index(
                        fields=["user", "event_type"],
                        name="analytics_e_user_id_11f9a1_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="analytics_e_content_a81fe0_idx",
                    ),
                ],
            },
        ),
    ]
