# Generated by Django 4.2.27 on 2025-12-15 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="provideranalytics",
            old_name="reviews_count",
            new_name="total_views",
        ),
    ]
