# Generated by Django 4.2.27 on 2025-12-15 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=30, verbose_name="Event type"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                        ],
                        max_length=10,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "Arabic"), ("en", "English")],
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subject template"
                    ),
                ),
                ("body_template", models.TextField(verbose_name="Body template")),
                (
                    "variables",
                    models.JSONField(default=list, verbose_name="Template variables"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["event_type", "channel", "-version"],
                "unique_together": {("event_type", "channel", "language", "version")},
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "email_messages",
                    models.BooleanField(
                        default=True, verbose_name="Email for messages"
                    ),
                ),
                (
                    "email_bookings",
                    models.BooleanField(
                        default=True, verbose_name="Email for bookings"
                    ),
                ),
                (
                    "email_reviews",
                    models.BooleanField(default=True, verbose_name="Email for reviews"),
                ),
                (
                    "email_payments",
                    models.BooleanField(
                        default=True, verbose_name="Email for payments"
                    ),
                ),
                (
                    "email_marketing",
                    models.BooleanField(default=False, verbose_name="Marketing emails"),
                ),
                (
                    "sms_bookings",
                    models.BooleanField(default=True, verbose_name="SMS for bookings"),
                ),
                (
                    "sms_payments",
                    models.BooleanField(default=True, verbose_name="SMS for payments"),
                ),
                (
                    "sms_urgent",
                    models.BooleanField(
                        default=True, verbose_name="SMS for urgent notifications"
                    ),
                ),
                (
                    "push_messages",
                    models.BooleanField(default=True, verbose_name="Push for messages"),
                ),
                (
                    "push_bookings",
                    models.BooleanField(default=True, verbose_name="Push for bookings"),
                ),
                (
                    "push_reviews",
                    models.BooleanField(default=True, verbose_name="Push for reviews"),
                ),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Digest frequency",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Quiet hours start"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Quiet hours end"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Cairo", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "New Message"),
                            ("booking", "Booking Update"),
                            ("review", "New Review"),
                            ("payment", "Payment Update"),
                            ("service_approved", "Service Approved"),
                            ("service_rejected", "Service Rejected"),
                            ("account_verified", "Account Verified"),
                            ("system", "System Notification"),
                            ("badge_earned", "Badge Earned"),
                            ("trust_update", "Trust Update"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="Arabic title"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="English title"
                    ),
                ),
                ("message_ar", models.TextField(verbose_name="Arabic message")),
                (
                    "message_en",
                    models.TextField(blank=True, verbose_name="English message"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email sent"),
                ),
                (
                    "sms_sent",
                    models.BooleanField(default=False, verbose_name="SMS sent"),
                ),
                (
                    "push_sent",
                    models.BooleanField(
                        default=False, verbose_name="Push notification sent"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
