# Generated by Django 4.2.7 on 2026-03-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
